# Navigation Links
#   To link a homepage section, use a hash `#` followed by the section ID.
#   The weight parameter defines the order that the links appear.

main:
  - name: Highlights
    url: /#projects
    weight: 10
  # - name: Experience & Education
  #   url: /#experience
  #   weight: 20
  - name: Research & Tech Stack
    url: /#skills
    weight: 30
  # - name: Hobbies & Interests
  #   url: /#hobbies
  #   weight: 31
  - name: Publications
    url: /#publications
    weight: 35
  - name: Contact
    url: /#contact
    weight: 50

footer:
  - name: Impressum
    url: /impressum/
    weight: 10
  - name: Datenschutz
    url: /datenschutz/
    weight: 20
