services:
  hugo:
    image: hugomods/hugo:std-exts
    # Use a shell command to install dependencies before starting the server
    command: >
      sh -c "npm install && hugo server --bind 0.0.0.0 --disableFastRender"
    working_dir: /src
    volumes:
      - .:/src
      # Persistent cache for node_modules and hugo modules improves speed
      - hugo_cache:/tmp/hugo_cache
      - node_modules:/src/node_modules
    ports:
      - "1313:1313"

volumes:
  hugo_cache:
  node_modules: